name: pipeline

on: push

jobs:
 ubuntu: 
  runs-on: ubuntu-latest
  steps: 
   -run: date
windows:
 runs-on: windows-latest
  steps: 
   -run: date
depends-on:
 needs: [ubuntu, windows]
 runs-on: macos-latest
  steps: 
   -run: date
